import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { IdProvider } from "@/components/providers/id-provider";
import { AuthProvider } from "@/components/providers/session-provider";
import { RoleAccessProvider } from "@/components/providers/role-access-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <AuthProvider>
          <RoleAccessProvider>
            <IdProvider>
              {children}
            </IdProvider>
          </RoleAccessProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
